version: 2

models:
  - name: command_executions
    description: Events of each instance of command execution by user within the Warp Terminal
    columns:
      - name: user_id
        description: Unique identifier for user
        data_type: varchar
      - name: event_timestamp
        description: Event timestamp of command execution
        data_type: timestamp(9)

  - name: users
    description: Events of each instance of command execution by user within the Warp Terminal
    columns:
      - name: user_id
        description: Unique identifier for user
        data_type: varchar
      - name: account_created_timestamp
        description: Timestamp of user account creation
        data_type: timestamp(9)
      - name: role
        description: Developer role user claimed to be
        data_type: varchar