version: 2

models:
  - name: stg_command_executions
    description: Events of each instance of command execution by user within the Warp Terminal
    columns:
      - name: user_id
        description: Unique identifier for user
        data_type: varchar
        data_tests:
          - not_null
      - name: event_ts
        description: Event timestamp of command execution
        data_type: timestamp(9)
        data_tests:
          - not_null